# -*- coding: utf-8 -*-
"""imgProcLab3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18VSRToBrDlSXHHs45bgi3nUeqFzv1oYd
"""

import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

img = cv.imread('test.jpg')
img_rgb = cv.cvtColor(img, cv.COLOR_BGR2RGB)

(h, w, d) = img_rgb.shape
angle = -100
scale = 1.0
center = (w // 2, h // 2)
M = cv.getRotationMatrix2D(center, angle, scale)

print(M)
rotated = cv.warpAffine(img_rgb, M, (w, h))
cropped_img = rotated[60:310]
plt.imshow(cropped_img)

img_rgb.shape

print(f'Диапазон яркостей: {np.min(img_rgb)} - {np.max(img_rgb)}')

'''Исходное изображение'''
plt.figure(figsize=(15, 10))

plt.subplot(2, 3, 1)
plt.imshow(cropped_img)
plt.title('1. Исходное изображение')
plt.axis('off')

def getSSIM(i1, i2):
    C1 = 6.5025  # для 8-битного изоражения
    C2 = 58.5225  # для 8-битного изоражения
    # INITS
    I1 = np.float32(i1)
    I2 = np.float32(i2)
    I2_2 = I2 * I2  # I2^2
    I1_2 = I1 * I1  # I1^2
    I1_I2 = I1 * I2  # I1 * I2

    mu1 = cv.GaussianBlur(I1, (11, 11), 1.5)
    mu2 = cv.GaussianBlur(I2, (11, 11), 1.5)
    mu1_2 = mu1 * mu1
    mu2_2 = mu2 * mu2
    mu1_mu2 = mu1 * mu2
    sigma1_2 = cv.GaussianBlur(I1_2, (11, 11), 1.5)
    sigma1_2 -= mu1_2
    sigma2_2 = cv.GaussianBlur(I2_2, (11, 11), 1.5)
    sigma2_2 -= mu2_2
    sigma12 = cv.GaussianBlur(I1_I2, (11, 11), 1.5)
    sigma12 -= mu1_mu2
    t1 = 2 * mu1_mu2 + C1
    t2 = 2 * sigma12 + C2
    t3 = t1 * t2  # t3 = ((2*mu1_mu2 + C1).*(2*sigma12 + C2))
    t1 = mu1_2 + mu2_2 + C1
    t2 = sigma1_2 + sigma2_2 + C2
    t1 = t1 * t2  # t1 =((mu1_2 + mu2_2 + C1).*(sigma1_2 + sigma2_2 + C2))
    ssim_map = cv.divide(t3, t1)  # ssim_map =  t3./t1;
    ssim = cv.mean(ssim_map)  # mssim = average of ssim map
    ssim = ssim[:3]
    return ssim

def getPSNR(I1, I2):
    s1 = cv.absdiff(I1, I2)  #|I1 - I2| - модуль разницы двух изображений
    s1 = np.float32(s1)
    s1 = s1 * s1  # |I1 - I2|^2
    sse = s1.sum()  # сумма элементов в каждом канале
    if sse <= 1e-10:  # сумма каналов
        return 0
    else:
        shape = I1.shape
        p=1
        for i in shape:
          p *= i
        mse = 1.0 * sse /p
        psnr = 10.0 * np.log10((255 * 255) / mse)
        return psnr

median_image1 = cv.medianBlur(cropped_img, 3)
median_image2 = cv.medianBlur(cropped_img, 5)

gs = plt.GridSpec(2, 2)
plt.subplot(gs[2])
plt.imshow(median_image2, cmap='gray')
psnr = getPSNR(cropped_img, median_image1)
ssim = getSSIM(cropped_img, median_image1)
plt.title(f'Восстановленное изображение \n '
          f'медианным фильтром 3х3 \n'
          f'PSNR = {psnr:.3f} \n SSIM = {ssim[0]:.3f}')