# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14kdg1Xt5ZZxlffVii1k3rZfINq71G8Fz
"""

import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import colors
from matplotlib.colors import hsv_to_rgb

img = cv.imread("./tomatoes.jpg")
imgRGB = cv.cvtColor(img, cv.COLOR_BGR2RGB)
plt.imshow(imgRGB)
plt.show()

imgHSV = cv.cvtColor(imgRGB, cv.COLOR_RGB2HSV)

h, s, v = cv.split(imgHSV)
fig = plt.figure()
axis = fig.add_subplot(1, 1, 1, projection="3d")

axis.scatter(h.flatten(), s.flatten(), v.flatten(), facecolors=pixel_colors, marker=".")
axis.set_xlabel("Hue")
axis.set_ylabel("Saturation")
axis.set_zlabel("Value")
plt.show()

#                      H   S   V
lower_blue = np.array([0,160,130])
upper_blue = np.array([20,255,255])
lo_square = np.full((10, 10, 3), lower_blue, dtype=np.uint8) / 255.0
do_square = np.full((10, 10, 3), upper_blue, dtype=np.uint8) / 255.0

plt.subplot(1, 2, 1)
plt.imshow(hsv_to_rgb(lo_square))
plt.subplot(1, 2, 2)
plt.imshow(hsv_to_rgb(do_square))
plt.show()

mask = cv.inRange(imgHSV, lower_blue, upper_blue) # make mask
result = cv.bitwise_and(imgRGB, imgRGB, mask=mask)

plt.figure(figsize=(15,20))
plt.subplot(1, 3, 1)
plt.imshow(imgRGB)
plt.subplot(1, 3, 2)
plt.imshow(mask, cmap="gray")
plt.subplot(1, 3, 3)
plt.imshow(result)
plt.show()

image_with_filtered_boxes = result.copy() # копируем результат маски
area_threshold = 100 # можно подогнать порог

for contour in contours:
    area = cv.contourArea(contour)

    if area > area_threshold:
        x, y, w, h = cv.boundingRect(contour) # размер прямоугольника
        cv.rectangle(imgRGB, (x, y), (x + w, y + h), (0, 255, 0), 2) # рисуем

plt.figure(figsize=(10, 10))
plt.imshow(imgRGB)
plt.title('результат')
plt.show()